### ISSUE TITLE
Add HtmlHint to overcommit.yml

### ISSUE THREAD

**Issue by woodpigeon** [EnvironmentAgency/before_commit#29]
HtmlHint is supported [out of the box](https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/pre_commit/html_hint.rb) by adding a section to overcommit.yml
(I haven't tested this yet so please hold off before tested)
I think it will pick up the default config file `.htmlhintrc` (already in ./source) without having to specify it with e.g. `flags: "-c ./htmlhintrc"`

```yaml
  HtmlHint:
    enabled: false
    description: 'Analyze with HTMLHint'
    required_executable: 'htmlhint'
    install_command: 'npm install -g htmlhint'
    include: 'app/views/**/*.html.erb'
```
